---

base_locale: en
locales: [en]

ignore_unused:
  - "decidim.components.extra_user_fields.name"
  - activemodel.attributes.user.*
  - activemodel.errors.models.user.*
  - decidim.admin.extra_user_fields.menu.title
  - decidim.admin.extra_user_fields.insights.*
  - decidim.extra_user_fields.genders.*
  - decidim.extra_user_fields.age_ranges.*

ignore_missing:
  - decidim.participatory_processes.scopes.global
  - decidim.admin.exports.notice
